/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : DMA.c
**     Project     : psi3441-frdm
**     Processor   : MKL25Z128VLK4
**     Component   : Init_DMA
**     Version     : Component 01.002, Driver 01.02, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-06-10, 19:06, # CodeGen: 69
**     Abstract    :
**          This file implements the DMA (DMA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : DMA
**          Device                                         : DMA
**          Clock gate for DMA                             : Enabled
**          Clock gate for DMA multiplexor 0               : Enabled
**          Channels                                       : 
**            Channel 0                                    : Initialize
**              Settings                                   : 
**                Transfer mode                            : Cycle-steal
**                Auto disable external request            : Disabled
**                Asynchronous request                     : Disabled
**                Auto align                               : Disabled
**                Channel links settings                   : 
**                  Link channel control                   : No link
**                  Link channel 1 (LCH1)                  : DMA channel 1
**                  Link channel 2 (LCH2)                  : DMA channel 1
**                Data source                              : 
**                  External object declaration            : #include "PWM.h"
**                  Address                                : PWMBuffer
**                  Address increment                      : Enabled
**                  Transfer size                          : 16-bit
**                  Address modulo                         : 256 Bytes
**                Data destination                         : 
**                  External object declaration            : 
**                  Address                                : 0x40038018
**                  Address increment                      : Disabled
**                  Transfer size                          : 16-bit
**                  Address modulo                         : Buffer disabled
**                Byte count                               : 524288
**              Pins/Signals                               : 
**                DMA MUX settings                         : 
**                  Channel state                          : Enabled
**                  Channel periodic trigger               : Disabled
**                  Channel request                        : TPM1_Overflow_DMA_Request
**                  Channel request signal                 : 
**              Interrupts                                 : 
**                DMA transfer done interrupt              : 
**                  Interrupt                              : INT_DMA0
**                  Interrupt request                      : Enabled
**                  Interrupt priority                     : 0 (Highest)
**                  ISR Name                               : DMA0_IRQHandler
**                  DMA transfer interrupt                 : Enabled
**              Initialization                             : 
**                External request                         : Disabled
**                Start DMA transfer                       : No
**            Channel 1                                    : Initialize
**              Settings                                   : 
**                Transfer mode                            : Cycle-steal
**                Auto disable external request            : Disabled
**                Asynchronous request                     : Disabled
**                Auto align                               : Disabled
**                Channel links settings                   : 
**                  Link channel control                   : No link
**                  Link channel 1 (LCH1)                  : DMA channel 0
**                  Link channel 2 (LCH2)                  : DMA channel 0
**                Data source                              : 
**                  External object declaration            : #include "DAC.h"
**                  Address                                : DACBuffer
**                  Address increment                      : Enabled
**                  Transfer size                          : 16-bit
**                  Address modulo                         : 256 Bytes
**                Data destination                         : 
**                  External object declaration            : 
**                  Address                                : 0x4003F000
**                  Address increment                      : Disabled
**                  Transfer size                          : 16-bit
**                  Address modulo                         : Buffer disabled
**                Byte count                               : 524288
**              Pins/Signals                               : 
**                DMA MUX settings                         : 
**                  Channel state                          : Enabled
**                  Channel periodic trigger               : Disabled
**                  Channel request                        : TPM1_Overflow_DMA_Request
**                  Channel request signal                 : 
**              Interrupts                                 : 
**                DMA transfer done interrupt              : 
**                  Interrupt                              : INT_DMA1
**                  Interrupt request                      : Enabled
**                  Interrupt priority                     : 0 (Highest)
**                  ISR Name                               : DMA1_IRQHandler
**                  DMA transfer interrupt                 : Enabled
**              Initialization                             : 
**                External request                         : Disabled
**                Start DMA transfer                       : No
**            Channel 2                                    : Do not initialize
**            Channel 3                                    : Do not initialize
**          Initialization                                 : 
**            Call Init method                             : no
**     Contents    :
**         Init - void DMA_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file DMA.c
** @version 01.02
** @brief
**          This file implements the DMA (DMA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup DMA_module DMA module documentation
**  @{
*/         

/* MODULE DMA. */

#include "DMA.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  DMA_Init (component Init_DMA)
**     Description :
**         This method initializes registers of the DMA module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/* Channel 0 data source external object declaration */
#include "PWM.h"
/* Channel 1 data source external object declaration */
#include "DAC.h"

void DMA_Init(void)
{
  /* SIM_SCGC7: DMA=1 */
  SIM_SCGC7 |= SIM_SCGC7_DMA_MASK;
  /* SIM_SCGC6: DMAMUX=1 */
  SIM_SCGC6 |= SIM_SCGC6_DMAMUX_MASK;
  /* DMAMUX0_CHCFG0: ENBL=0,TRIG=0,SOURCE=0 */
  DMAMUX0_CHCFG0 = DMAMUX_CHCFG_SOURCE(0x00);
  /* DMAMUX0_CHCFG1: ENBL=0,TRIG=0,SOURCE=0 */
  DMAMUX0_CHCFG1 = DMAMUX_CHCFG_SOURCE(0x00);
  /* DMAMUX0_CHCFG2: ENBL=0,TRIG=0,SOURCE=0 */
  DMAMUX0_CHCFG2 = DMAMUX_CHCFG_SOURCE(0x00);
  /* DMAMUX0_CHCFG3: ENBL=0,TRIG=0,SOURCE=0 */
  DMAMUX0_CHCFG3 = DMAMUX_CHCFG_SOURCE(0x00);
  /* DMA_DSR_BCR0: DONE=1 */
  DMA_DSR_BCR0 |= DMA_DSR_BCR_DONE_MASK;
  /* DMA_DSR_BCR1: DONE=1 */
  DMA_DSR_BCR1 |= DMA_DSR_BCR_DONE_MASK;
  /* DMA_SAR0 = PWMBuffer */
  DMA_SAR0 = (uint32_t)(PWMBuffer);
  /* DMA_SAR1 = DACBuffer */
  DMA_SAR1 = (uint32_t)(DACBuffer);
  /* DMA_DAR0 = 0x40038018 */
  DMA_DAR0 = (uint32_t)(0x40038018);
  /* DMA_DAR1 = 0x4003F000 */
  DMA_DAR1 = (uint32_t)(0x4003F000);
  /* DMA_DSR_BCR0: ??=0,CE=0,BES=0,BED=0,??=0,REQ=0,BSY=0,DONE=0,BCR=0x00080000 */
  DMA_DSR_BCR0 = DMA_DSR_BCR_BCR(0x00080000);
  /* DMA_DSR_BCR1: ??=0,CE=0,BES=0,BED=0,??=0,REQ=0,BSY=0,DONE=0,BCR=0x00080000 */
  DMA_DSR_BCR1 = DMA_DSR_BCR_BCR(0x00080000);
  /* DMA_DCR0: EINT=1,ERQ=0,CS=1,AA=0,??=0,??=0,??=0,??=0,EADREQ=0,SINC=1,SSIZE=2,DINC=0,DSIZE=2,START=0,SMOD=5,DMOD=0,D_REQ=0,??=0,LINKCC=0,LCH1=1,LCH2=1 */
  DMA_DCR0 = DMA_DCR_EINT_MASK |
             DMA_DCR_CS_MASK |
             DMA_DCR_SINC_MASK |
             DMA_DCR_SSIZE(0x02) |
             DMA_DCR_DSIZE(0x02) |
             DMA_DCR_SMOD(0x05) |
             DMA_DCR_DMOD(0x00) |
             DMA_DCR_LINKCC(0x00) |
             DMA_DCR_LCH1(0x01) |
             DMA_DCR_LCH2(0x01);
  /* DMA_DCR1: EINT=1,ERQ=0,CS=1,AA=0,??=0,??=0,??=0,??=0,EADREQ=0,SINC=1,SSIZE=2,DINC=0,DSIZE=2,START=0,SMOD=5,DMOD=0,D_REQ=0,??=0,LINKCC=0,LCH1=0,LCH2=0 */
  DMA_DCR1 = DMA_DCR_EINT_MASK |
             DMA_DCR_CS_MASK |
             DMA_DCR_SINC_MASK |
             DMA_DCR_SSIZE(0x02) |
             DMA_DCR_DSIZE(0x02) |
             DMA_DCR_SMOD(0x05) |
             DMA_DCR_DMOD(0x00) |
             DMA_DCR_LINKCC(0x00) |
             DMA_DCR_LCH1(0x00) |
             DMA_DCR_LCH2(0x00);
  /* DMAMUX0_CHCFG0: ENBL=1,TRIG=0,SOURCE=0x37 */
  DMAMUX0_CHCFG0 = (DMAMUX_CHCFG_ENBL_MASK | DMAMUX_CHCFG_SOURCE(0x37));
  /* DMAMUX0_CHCFG1: ENBL=1,TRIG=0,SOURCE=0x37 */
  DMAMUX0_CHCFG1 = (DMAMUX_CHCFG_ENBL_MASK | DMAMUX_CHCFG_SOURCE(0x37));
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      main.c
**      Events.c
**
** ###################################################################
PE_ISR(DMA0_IRQHandler)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      main.c
**      Events.c
**
** ###################################################################
PE_ISR(DMA1_IRQHandler)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END DMA. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
